<?php

/**
 * @file
 * Primary module hooks for Three.js module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * The minimum ThreeJS version we support.
 */
const THREEJS_MIN_PLUGIN_VERSION = 'r91';

/**
 * Implements hook_libraries_info().
 */
function threejs_libraries_info() {
  $libraries['three.js'] = [
    'name' => 'ThreeJS',
    'vendor url' => 'https://github.com/mrdoob/three.js',
    'download url' => 'https://github.com/mrdoob/three.js/archive/dev.zip',
    'version arguments' => [
      'file' => 'src/constants.js',
      'pattern' => '/v([\d.]+)/',
      'lines' => 1,
      'cols' => 24,
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_help().
 */
function threejs_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.threejs':
      $output = check_markup(file_get_contents(dirname(__FILE__) . '/help/readme.html'), 'full_html');
  }
  return $output;
}
